
spring.datasource.generate-unique-name=false

spring.datasource.url=jdbc:h2:mem:wiserate
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.name=wiserate
spring.datasource.username=root
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.path=/api/h2-console

spring.jpa.hibernate.ddl-auto=create-drop

#spring.datasource.generate-unique-name=false
logging.level.org.springframework.security=DEBUG

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

spring.devtools.restart.enabled=true

logging.level.com.wiserate=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{0} - %msg%n
