spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.web.resources.static-locations=classpath:/static/

spring.jpa.hibernate.ddl-auto=create-drop

logging.level.org.springframework.security=DEBUG

spring.devtools.restart.enabled=false

logging.level.com.wiserate=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{0} - %msg%n
